/*
 * Copyright (c) Terl Tech Ltd • 04/04/2020, 00:05 • goterl.com
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v2.0. If a copy of the MPL was not distributed with this
 * file, you can obtain one at http://mozilla.org/MPL/2.0/.
 */
plugins {
    id 'com.android.library'
    id 'com.vanniktech.maven.publish' version '0.34.0'
    id 'signing'
}

ext {
    artifactId = "lazysodium-android"
    groupId = "cz.mormegil"
    version = '6.0.1-SNAPSHOT'
    description = "Lazysodium (Android) makes it effortless for Android " +
            "developers to get started with Libsodium's cryptography. " +
            "(fork of the original library)"
    androidTestDir = "src/androidTest/java/com/goterl/lazysodium"
    javaTestDir = "../lazysodium-java/src/test/java/com/goterl/lazysodium"

    jUnitVersion = "4.13.2"
    androidXJUnitVersion = "1.3.0"
    androidXEspressoVersion = "3.7.0"
    androidXTestingCoreVersion = "2.2.0"
    androidXTestCoreVersion = "1.7.0"
    androidXTestRunnerVersion = "1.7.0"
    kotlinCoroutinesVersion = "1.6.4"
}

group = project.ext.groupId
version = project.ext.version

android {
    compileSdkVersion 36
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 36
        multiDexEnabled = true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        // Typically we would need to clear data between every run
        // but we don't need to in this test suite as we aren't
        // running conventional espresso tests. Speeds up tests 2x.
        // testInstrumentationRunnerArguments clearPackageData: 'true'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets.main {
        jniLibs.srcDirs = ['src/main/jniLibs']

        java {
            srcDir "../lazysodium-java/src/main/java"
            // Be sure to update lint.xml in the project root if any other
            // excluded files are added.
            exclude "com/goterl/lazysodium/utils/LibraryLoader.java"
            exclude "com/goterl/lazysodium/SodiumJava.java"
            exclude "com/goterl/lazysodium/LazySodiumJava.java"
            exclude "com/goterl/lazysodium/utils/Base64Java.java"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        resources {
            excludes += ['../lazysodium-java/src/test/java']
        }
    }


    testOptions {
        animationsDisabled = true
        execution = 'ANDROIDX_TEST_ORCHESTRATOR'
    }
    namespace = 'com.goterl.lazysodium'
    lint {
        lintConfig = file('lint.xml')
    }
}

void loadProps() {
    File secretPropsFile = project.rootProject.file('local.properties')
    if (secretPropsFile.exists()) {
        Properties p = new Properties()
        new FileInputStream(secretPropsFile).withCloseable { is ->
            p.load(is)
        }
        p.each { name, value ->
            ext[name] = value
        }
    } else {
        ext.isCi = true
    }
}

loadProps()

tasks.withType(Test).configureEach {
    testLogging {
        exceptionFormat = "full"
        events "started", "skipped", "passed", "failed"
        showStandardStreams = true
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'net.java.dev.jna:jna:5.17.0@aar'

    // Test libs
    testImplementation "junit:junit:$jUnitVersion"
    testImplementation "androidx.arch.core:core-testing:$androidXTestingCoreVersion"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:$kotlinCoroutinesVersion"
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$kotlinCoroutinesVersion"
    testImplementation "androidx.test:runner:$androidXTestRunnerVersion"

    androidTestImplementation "androidx.test:core:$androidXTestCoreVersion"
    androidTestImplementation "androidx.test.ext:junit:$androidXJUnitVersion"
    androidTestImplementation "androidx.test:rules:$androidXTestCoreVersion"
    androidTestImplementation "androidx.test:runner:$androidXTestRunnerVersion"
    androidTestUtil "androidx.test:orchestrator:1.6.1"
    androidTestImplementation "androidx.test.espresso:espresso-core:$androidXEspressoVersion"
    androidTestImplementation "androidx.test.espresso:espresso-contrib:$androidXEspressoVersion"
    androidTestImplementation "androidx.arch.core:core-testing:$androidXTestingCoreVersion"
}

// Tasks
signing {
    // This will use the GPG Agent
    // to sign the jar
    useGpgCmd()
    sign publishing.publications
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(project.ext.groupId, project.ext.artifactId, project.ext.version)

    pom {
        name = project.ext.artifactId
        description = project.ext.description
        url = 'https://github.com/mormegil-cz/lazysodium-android'
        licenses {
            license {
                name = 'Mozilla Public License, Version 2.0'
                url = 'https://www.mozilla.org/MPL/2.0/index.txt'
                distribution = 'repo'
            }
        }
        developers {
            developer {
                name = 'Terl Tech Ltd'
                email = 'hello@terl.co'
            }
            developer {
                name = 'mormegil-cz'
                email = 'mormegil@centrum.cz'
            }
        }
        scm {
            connection = 'scm:git:git://github.com/mormegil-cz/lazysodium-android.git'
            developerConnection = 'scm:git:ssh://github.com/mormegil-cz/lazysodium-android'
            url = 'https://github.com/mormegil-cz/lazysodium-android'
        }
    }
}
